# Generated by Django 3.2.7 on 2021-09-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
