# Generated by Django 3.2.7 on 2021-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_contact_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='screenshot',
            field=models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='contact/images'),
        ),
    ]
