# Generated by Django 3.2.7 on 2021-09-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_contact_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='screenshot',
            new_name='photo',
        ),
    ]
