# Generated by Django 3.2.7 on 2021-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_screenshot_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='media/contact/images'),
        ),
    ]
